ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "paymentIntentId" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "used" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "usedAt" TIMESTAMP(3);
